Update convert_sd_to_diffusers.py
convert_sd_to_diffusers.py not found, downloading...
Loading checkpoint: /content/models/poltergeistMix_v20.safetensors
Traceback (most recent call last):
  File "/content/convert_sd_to_diffusers.py", line 125, in <module>
    convert_model(args)
  File "/content/convert_sd_to_diffusers.py", line 20, in convert_model
    loaded_model_data = load_sd_model(args, is_load_checkpoint, load_dtype)
  File "/content/convert_sd_to_diffusers.py", line 47, in load_sd_model
    loaded_model_data = load_sd_model(args)
TypeError: load_sd_model() missing 2 required positional arguments: 'is_load_checkpoint' and 'load_dtype'